"""
Hero Cost Intelligence Domain Output Schemas
Standard Pydantic v2 schemas for structured extraction, synthesis, and SLM interaction.

Boundary Note:
These schemas represent advisory extractions and hypotheses.
Authoritative business calculations (OPEX, BOM, opportunity valuation, governance)
remain exclusively managed by deterministic pure-Python engines in Calculations/.
ToolCallOutputSchema represents an advisory proposal and does not authorize execution.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class IdeaDecompositionOutputSchema(BaseModel):
    """
    Structured extraction from raw, unstructured engineer/technician idea submissions.
    """
    category: str = Field(description="Primary idea category (e.g. LIGHTWEIGHTING, MATERIAL_SUBSTITUTION, PROCESS_OPTIMIZATION)")
    subcategory: Optional[str] = Field(default=None, description="Granular subcategory")
    target_component: str = Field(description="Target vehicle component or assembly (e.g. Handlebar, Brake Disc, Main Frame)")
    target_part_number: Optional[str] = Field(default=None, description="Exact 10-12 digit Hero part number if identified")
    target_vehicle_models: List[str] = Field(default_factory=list, description="Target vehicle models (e.g. SPLENDOR_PLUS, HF_DELUXE)")
    problem_statement: str = Field(description="Summary of current design limitation or inefficiency")
    technical_solution: str = Field(description="Specific engineering change proposed (material, geometry, process)")
    estimated_weight_reduction_grams: Optional[float] = Field(default=None, description="Proposed weight delta in grams")
    estimated_cost_saving_inr: Optional[float] = Field(default=None, description="Estimated piece-cost delta in INR")
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Extraction confidence score")


class EvidenceSynthesisOutputSchema(BaseModel):
    """
    SLM synthesis of grounded implementation evidence discovered across ECN/BOM hierarchy.
    """
    decision_summary: str = Field(description="Concise advisory explanation of evidence grounding state")
    primary_status: str = Field(description="Proposed status: CONFIRMED, PARTIAL, HISTORICAL, POTENTIAL, NO_EVIDENCE, INSUFFICIENT, CONFLICTING")
    supporting_reasons: List[str] = Field(default_factory=list, description="Bulleted evidence citations and observations")
    cited_ecn_numbers: List[str] = Field(default_factory=list, description="Referenced ECN / change order numbers")
    cited_part_numbers: List[str] = Field(default_factory=list, description="Referenced part numbers")
    requires_human_escalation: bool = Field(default=False, description="Flag indicating unresolved conflicting evidence or ambiguity")
    escalation_rationale: Optional[str] = Field(default=None, description="Reason for escalation if required")


class OpportunitySimulationOutputSchema(BaseModel):
    """
    Proposed opportunity parameters for financial simulation.
    Note: Calculations remain deterministic; these are suggested parameter bindings.
    """
    part_number: str = Field(description="Part number under evaluation")
    vehicle_model: str = Field(description="Target vehicle model code")
    suggested_cost_delta_inr: float = Field(description="Proposed piece cost reduction in INR per unit")
    estimated_annual_volume: int = Field(ge=0, description="Estimated vehicle production volume")
    estimated_tooling_investment_inr: Optional[float] = Field(default=None, description="One-time tooling or CAPEX investment")
    justification: str = Field(description="Technical rationale for suggested opportunity parameters")


class OpexBenchmarkingHypothesisSchema(BaseModel):
    """
    Proposed root-cause hypotheses for plant OPEX and utility variances.
    """
    plant_code: str = Field(description="Plant identifier (e.g. HARIDWAR, DHARUHERA, NEEMRANA)")
    category: str = Field(description="Utility category: ELECTRICITY, WATER, COMPRESSED_AIR, NATURAL_GAS")
    observed_specific_consumption: float = Field(ge=0.0, description="Specific consumption rate per vehicle")
    variance_driver_hypotheses: List[str] = Field(default_factory=list, description="Proposed operational drivers explaining benchmark variance")
    recommended_investigation: str = Field(description="Recommended engineering or operational shop-floor investigation")


class ToolCallOutputSchema(BaseModel):
    """
    Structured tool invocation request generated by the SLM.
    Security Guardrail: This is an advisory invocation proposal ONLY.
    Tool authorization, allowlist gating, schema checking, and execution occur in AI-11.
    """
    tool_name: str = Field(description="Requested sandboxed tool identifier")
    arguments: Dict[str, Any] = Field(default_factory=dict, description="Structured key-value arguments for the tool")
    intent_description: str = Field(description="Natural language summary of why this tool call is needed")
    expected_output_type: str = Field(default="JSON", description="Expected result representation")
